version: '3'
services:
  mongo:
    image: mongo:3.6
    # restart: always
    # ports:
    #   - 27018:27017
  web:
    build: .
    ports:
     - "8080:8080"
    environment:
     - MONGODB_URI=mongodb://mongo:27017/testi 
    links:
     - mongo 
    depends_on: 
     - mongo 
    volumes:
     - .:/starter
     - /starter/node_modules
     